'use client';
import { useEffect, useRef } from 'react';

export type MaterialKind = 'orbit' | 'launch' | 'burst' | 'beam' | 'repair';
export type MaterialSettings = { density: number; speed: number; glow: number; scale: number };
const palette: Record<MaterialKind, string> = { orbit: '140,186,255', launch: '203,165,255', burst: '123,214,255', beam: '244,201,125', repair: '255,116,139' };

export function MaterialCanvas({ kind, settings }: { kind: MaterialKind; settings: MaterialSettings }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => { const canvas = ref.current, context = canvas?.getContext('2d'); if (!canvas || !context) return; let w = 0, h = 0, frame = 0; const dots = Array.from({ length: 220 }, (_, i) => ({ a: i * 2.399, r: .18 + (i * 47 % 100) / 100, p: i * .73 })); const resize = () => { const box = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio, 2); w = box.width; h = box.height; canvas.width = w * dpr; canvas.height = h * dpr; context.setTransform(dpr, 0, 0, dpr, 0, 0); }; const watch = new ResizeObserver(resize); watch.observe(canvas); resize(); const draw = (now: number) => { const t = now / 1000 * settings.speed, color = palette[kind], cx = w / 2, cy = h / 2, scale = settings.scale; context.fillStyle = 'rgba(3,6,10,.18)'; context.fillRect(0, 0, w, h); const haze = context.createRadialGradient(cx, cy, 0, cx, cy, 210 * scale); haze.addColorStop(0, `rgba(${color},${.12 * settings.glow})`); haze.addColorStop(1, 'rgba(0,0,0,0)'); context.fillStyle = haze; context.fillRect(0, 0, w, h); context.save(); context.translate(cx, cy); context.scale(scale, scale); context.translate(-cx, -cy); if (kind === 'orbit') { for (let ring = 0; ring < 4; ring++) { context.strokeStyle = `rgba(${color},${.13 + ring * .035})`; context.setLineDash(ring % 2 ? [2, 7] : []); context.beginPath(); context.ellipse(cx, cy, 60 + ring * 31, 28 + ring * 14, t * (.08 + ring * .018), .2, Math.PI * 1.7); context.stroke(); } dots.slice(0, settings.density).forEach((dot) => point(context, cx + Math.cos(dot.a + t * .38) * dot.r * 175, cy + Math.sin(dot.a + t * .38) * dot.r * 76, color, .2 + dot.r * .65)); }
  if (kind === 'launch') { const source = { x: cx - 220, y: cy + 75 }, target = { x: cx + 210, y: cy - 55 }; point(context, source.x, source.y, color, 1.4); point(context, target.x, target.y, color, 1.7); for (let i = 0; i < settings.density; i++) { const q = (t * .28 + i / settings.density) % 1, bend = Math.sin(i * 2.3) * 80, x = (1 - q) ** 2 * source.x + 2 * (1 - q) * q * cx + q ** 2 * target.x, y = (1 - q) ** 2 * source.y + 2 * (1 - q) * q * (cy + bend) + q ** 2 * target.y; point(context, x, y, color, .28 + (i % 4) * .12); } }
  if (kind === 'burst') { const p = (t * .42) % 1; for (let ring = 0; ring < 3; ring++) { context.strokeStyle = `rgba(${color},${(1 - ((p + ring / 3) % 1)) * .28})`; context.beginPath(); context.ellipse(cx, cy, 22 + ((p + ring / 3) % 1) * 220, 12 + ((p + ring / 3) % 1) * 110, .22, 0, Math.PI * 2); context.stroke(); } dots.slice(0, settings.density).forEach((dot) => { const distance = ((t * .32 + dot.r) % 1) * 230; point(context, cx + Math.cos(dot.a) * distance, cy + Math.sin(dot.a) * distance * .55, color, .18 + dot.r * .55); }); }
  if (kind === 'beam') { const a = { x: cx - 240, y: cy + 55 }, b = { x: cx + 225, y: cy - 35 }; context.lineWidth = 1; context.strokeStyle = `rgba(${color},${.35 * settings.glow})`; context.beginPath(); context.moveTo(a.x, a.y); context.lineTo(b.x, b.y); context.stroke(); for (let i = 0; i < settings.density; i++) { const q = (t * .34 + i / settings.density) % 1; point(context, a.x + (b.x - a.x) * q, a.y + (b.y - a.y) * q, color, .35 + (i % 3) * .13); } for (let i = 0; i < settings.density / 2; i++) { const q = (t * .28 + i / (settings.density / 2)) % 1; point(context, b.x + (a.x - b.x) * q, b.y + (a.y - b.y) * q + Math.sin(i * 2.1) * 12, '139,236,255', .24); } }
  if (kind === 'repair') { const p = (t * .26) % 1; context.strokeStyle = `rgba(255,104,122,${.45 * (1 - p)})`; for (let i = 0; i < 8; i++) { context.beginPath(); context.moveTo(cx - 35, cy); context.lineTo(cx - 35 + Math.cos(i) * (30 + p * 145), cy + Math.sin(i) * (24 + p * 80)); context.stroke(); } context.strokeStyle = 'rgba(193,177,255,.35)'; context.beginPath(); context.moveTo(cx - 225, cy + 100); context.bezierCurveTo(cx - 40, cy + 170, cx + 25, cy - 130, cx + 205, cy - 48); context.stroke(); point(context, cx + 205, cy - 48, '185,245,138', 1.6); }
  point(context, cx, cy, color, 1.8); context.restore(); frame = requestAnimationFrame(draw); }; frame = requestAnimationFrame(draw); return () => { cancelAnimationFrame(frame); watch.disconnect(); }; }, [kind, settings]); return <canvas ref={ref} className="size-full" />;
}
function point(context: CanvasRenderingContext2D, x: number, y: number, color: string, alpha: number) { context.fillStyle = `rgba(${color},${alpha})`; context.shadowBlur = 12 * alpha; context.shadowColor = `rgb(${color})`; context.beginPath(); context.arc(x, y, .7 + alpha * 2.2, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; }
