'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Pause, Play, RotateCcw, Telescope } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AgentEvent, AgentEventKind, AgentZone, eventKinds, mockRun } from '@/features/agent-events';
import { eventLinks, fieldZones } from '@/features/execution-field/config';

const zones = fieldZones;
const materialPreviews: [string, AgentEventKind][] = [['SEARCH BURST','search_started'],['MCP BEAM','tool_call'],['FIELD ORBIT','skill_loaded'],['CONTEXT COLLAPSE','context_compacted']];

export function MaterialLab() {
  const [cursor,setCursor]=useState(-1),[playing,setPlaying]=useState(false),[tilt,setTilt]=useState(false),[selected,setSelected]=useState<AgentZone>('context');
  const emptySatellites = (): Record<AgentZone, AgentEvent[]> => ({ context:[], think:[], skills:[], mcp:[], search:[], repo:[], tools:[], test:[], memory:[] });
  const [satellites,setSatellites]=useState<Record<AgentZone,AgentEvent[]>>(emptySatellites);
  const [beam,setBeam]=useState<{from:AgentZone;to:AgentZone;color:string;id:number}|null>(null); const viewport=useRef<HTMLDivElement>(null);
  const event=cursor>=0?mockRun[cursor]:null; const counts=useMemo(()=>Object.fromEntries(Object.entries(satellites).map(([key,value])=>[key,value.length])) as Record<AgentZone,number>,[satellites]);
  const runEvent=useCallback((index:number)=>{ if(index>=mockRun.length){setPlaying(false);return;} const next=mockRun[index],kind=eventKinds[next.kind];setCursor(index);setSelected(next.target);setSatellites(previous=>({...previous,[next.target]:[...previous[next.target],next]}));const link=eventLinks[next.kind];if(link)setBeam({from:link[0],to:link[1],color:kind.color,id:Date.now()});},[]);
  useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setCursor(current=>{const next=current+1;if(next>=mockRun.length){setPlaying(false);return current;} queueMicrotask(()=>runEvent(next));return next;}),1050);return()=>window.clearInterval(id)},[playing,runEvent]);
  const reset=()=>{setPlaying(false);setCursor(-1);setBeam(null);setSatellites(emptySatellites())};
  const preview=(kind:AgentEventKind)=>{const config=eventKinds[kind];const next:AgentEvent={id:`preview-${Date.now()}`,at:0,kind,title:kind.replaceAll('_',' '),detail:'Material preview',target:config.zone};setSelected(config.zone);setSatellites(p=>({...p,[config.zone]:[...p[config.zone],next]}));const link=eventLinks[kind];if(link)setBeam({from:link[0],to:link[1],color:config.color,id:Date.now()});};
  const metric={context:`${(8.2+Math.max(0,cursor+1)*.31).toFixed(1)}k / 200k`,memory:cursor>=21?'1 loaded':'0 loaded',skills:cursor>=3?'1 active':'0 active',mcp:cursor>=4?'github · online':'offline'};
  return <><div className="star-field"/><header className="fixed inset-x-0 top-0 z-20 flex h-11 items-center justify-between border-b border-blue-200/10 bg-slate-950/70 px-[18px] backdrop-blur-md"><div className="text-[11px] tracking-[.16em] text-slate-100"><span className="text-blue-300">AGENT</span>VISUAL <span className="text-slate-500">/ material lab</span></div><nav className="flex items-center gap-1"><Button variant="ghost" onClick={()=>setTilt(v=>!v)}><Telescope size={13}/>FIELD TILT</Button><Button variant="ghost" onClick={reset}><RotateCcw size={13}/>REPLAY</Button></nav></header>
  <aside className="fixed bottom-4 left-4 top-[60px] z-20 w-56 border border-blue-200/10 bg-slate-950/65 p-3.5 backdrop-blur-xl"><p className="mb-3 text-[9px] uppercase tracking-[.16em] text-blue-200/60">Live state</p>{[['Context',metric.context],['Memory',metric.memory],['Skills',metric.skills],['MCP',metric.mcp]].map(([label,value])=><div key={label} className="border-b border-blue-100/10 py-2.5 text-slate-400"><span>{label}</span><strong className="float-right font-medium text-blue-100">{value}</strong></div>)}<div className="mt-5 text-[9px] uppercase tracking-[.16em] text-blue-200/60">Active tools</div><div className="mt-2 flex flex-wrap gap-1">{['rg','read_file','apply_patch','github.search_code'].map(tool=><span className="rounded-full border border-blue-200/15 px-1.5 py-0.5 text-[10px] text-slate-400" key={tool}>{tool}</span>)}</div></aside>
  <main ref={viewport} className="fixed bottom-[86px] left-64 right-[282px] top-11 z-10 overflow-hidden [perspective:950px]"><div className={`world ${tilt?'tilt':''}`}>{(Object.entries(zones) as [AgentZone,typeof zones[AgentZone]][]).map(([name,zone],i)=><div key={name} onClick={()=>setSelected(name)} className={`zone ${selected===name?'selected':''} ${event?.target===name?'active':''}`} style={{left:`${zone.x}%`,top:`${zone.y}%`,['--rgb' as string]:zone.rgb,['--speed' as string]:`${4+i%4}s`,['--tilt' as string]:`${i*23}deg`,scale:`${Math.min(1+counts[name]*.035,1.28)}`}}><i className="core"/><span className="zone-label">{name}</span>{satellites[name].map((s,n)=><i key={s.id} className="satellite" style={{['--duration' as string]:`${9+(n%5)*2}s`,['--from' as string]:`${n*53}deg`,['--radius' as string]:`${34+Math.min(n,7)*7}px`}}><small>{s.title==='Read'||s.title==='Patch'?s.detail.split(' · ')[0]:s.title}</small>{n>2&&<i className="satellite child" style={{['--duration' as string]:`${7+n}s`,['--from' as string]:`${n*71}deg`,['--radius' as string]:`${18+n%3*5}px`}}/>}</i>)}</div>)}</div>{beam&&<Beam beam={beam} viewport={viewport}/>}</main>
  <div className="pointer-events-none fixed left-64 right-[282px] top-14 z-20 flex justify-center gap-1">{materialPreviews.map(([label,kind])=><Button key={kind} className="pointer-events-auto bg-slate-950/60" onClick={()=>preview(kind)}>{label}</Button>)}</div>
  <aside className="fixed bottom-4 right-4 top-[60px] z-20 w-[250px] border border-blue-200/10 bg-slate-950/65 p-3.5 backdrop-blur-xl"><p className="mb-3 text-[9px] uppercase tracking-[.16em] text-blue-200/60">Event inspector</p>{event?<><Panel title={event.title} selected text={event.detail}/><Panel title={event.kind} text={`material: ${eventKinds[event.kind].effect}\ntarget: ${event.target}\nt + ${(event.at/1000).toFixed(1)}s · ${cursor+1}/${mockRun.length}`}/></>:<Panel title="Replay ready" text="Press play to grow an execution field from a sparse initial state."/>}<div className="mt-5 text-[9px] uppercase tracking-[.16em] text-blue-200/60">Effect materials</div><Panel title="Mass" text="usage → radius, density, orbit speed"/><Panel title="Beam" text="cross-system request / function call"/><Panel title="Absorption" text="result reaches target → cluster grows"/><Panel title="History" text="completed child events remain as dim satellites"/></aside>
  <section className="fixed inset-x-0 bottom-0 z-20 grid h-[86px] grid-cols-[230px_1fr_245px] items-center gap-4 border-t border-blue-200/10 bg-slate-950/85 px-[18px] backdrop-blur-xl"><div className="flex gap-2"><Button onClick={()=>{if(cursor>=mockRun.length-1)reset();setPlaying(v=>!v)}}>{playing?<Pause size={13}/>:<Play size={13}/>} {playing?'PAUSE':'PLAY'}</Button><Button onClick={()=>runEvent(cursor+1)}>STEP</Button><Button onClick={reset}>RESET</Button></div><div className="flex h-10 items-center gap-[5px] overflow-hidden">{mockRun.map((item,index)=><button aria-label={item.detail} onClick={()=>runEvent(index)} key={item.id} className={`size-[7px] shrink-0 rounded-full transition-all ${index<cursor?'opacity-80':index===cursor?'scale-[1.75] opacity-100':'opacity-30'}`} style={{background:eventKinds[item.kind].color,boxShadow:`0 0 8px ${eventKinds[item.kind].color}`}}/>)}</div><div className="overflow-hidden text-right text-[11px] text-slate-500"><b className="block font-medium text-blue-100">{event?.title??'Mock coding-agent run'}</b>{event?.detail??'22 semantic events queued'}</div></section></>;
}
function Panel({title,text,selected=false}:{title:string;text:string;selected?:boolean}){return <div className={`mb-3 border-l border-blue-200/30 bg-slate-900/35 p-2 text-[10px] ${selected?'outline outline-1 outline-offset-[5px] outline-blue-200/60':''}`}><b className="font-medium text-blue-100">{title}</b><p className="mb-0 mt-1 whitespace-pre-line text-slate-400">{text}</p></div>}
function Beam({beam,viewport}:{beam:{from:AgentZone;to:AgentZone;color:string;id:number};viewport:React.RefObject<HTMLDivElement>}){const from=zones[beam.from],to=zones[beam.to];const dx=to.x-from.x,dy=to.y-from.y;const angle=Math.atan2(dy,dx);return <i key={beam.id} className="beam" style={{left:`${from.x}%`,top:`${from.y}%`,width:`${Math.hypot(dx,dy)}%`,['--beam' as string]:hexRgb(beam.color),['--angle' as string]:`${angle}rad`}}/>}
function hexRgb(hex:string){return `${parseInt(hex.slice(1,3),16)},${parseInt(hex.slice(3,5),16)},${parseInt(hex.slice(5,7),16)}`}
