'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Aperture, Pause, Play, RotateCcw, Telescope } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AgentEvent, AgentEventKind, AgentZone, currentSessionEvents, eventKinds } from '@/features/agent-events';
import { eventLinks, fieldZones } from '@/features/execution-field/config';

type Mode = 'execution' | 'material';
type Beam = { from: AgentZone; to: AgentZone; color: string; id: number };
const zones = fieldZones;
const scenes: [string, AgentEventKind, string][] = [
  ['ORBIT SYSTEM', 'skill_loaded', 'satellites accumulate and deform the parent field'],
  ['SEARCH BURST', 'search_started', 'a query releases a scanning shockwave'],
  ['MCP BEAM', 'tool_call', 'a request crosses into an external station'],
  ['RETURN FLOW', 'tool_result', 'result particles stream back into context'],
  ['REPAIR WAVE', 'test_failed', 'failure bends the execution path toward retry'],
];
const empty = (): Record<AgentZone, AgentEvent[]> => ({ context: [], think: [], skills: [], mcp: [], search: [], repo: [], tools: [], test: [], memory: [] });
const particles = (name: string) => Array.from({ length: 30 }, (_, i) => ({ id: `${name}-${i}`, x: 13 + (i * 37 + name.length * 7) % 75, y: 13 + (i * 53 + name.length * 11) % 75, size: 1 + i % 3, delay: `${(i % 10) * -.45}s`, duration: `${4 + i % 6}s` }));

export function ExecutionReplay() { return <AgentVisual mode="execution" />; }
export function MaterialLab() { return <AgentVisual mode="material" />; }

function AgentVisual({ mode }: { mode: Mode }) {
  const [cursor, setCursor] = useState(-1), [playing, setPlaying] = useState(false), [tilt, setTilt] = useState(false), [selected, setSelected] = useState<AgentZone>('context'), [satellites, setSatellites] = useState<Record<AgentZone, AgentEvent[]>>(empty), [beam, setBeam] = useState<Beam | null>(null), [scene, setScene] = useState<string | null>(null);
  const particleMap = useMemo(() => Object.fromEntries(Object.keys(zones).map((name) => [name, particles(name)])) as Record<AgentZone, ReturnType<typeof particles>>, []);
  const event = cursor >= 0 ? currentSessionEvents[cursor] : null;
  const counts = useMemo(() => Object.fromEntries(Object.entries(satellites).map(([key, value]) => [key, value.length])) as Record<AgentZone, number>, [satellites]);
  const run = useCallback((index: number) => { if (index >= currentSessionEvents.length) { setPlaying(false); return; } const next = currentSessionEvents[index]; setCursor(index); setSelected(next.target); setSatellites((old) => ({ ...old, [next.target]: [...old[next.target], next] })); const link = eventLinks[next.kind]; if (link) setBeam({ from: link[0], to: link[1], color: eventKinds[next.kind].color, id: Date.now() }); }, []);
  useEffect(() => { if (mode !== 'execution') return; const history = currentSessionEvents.slice(0, 7); setCursor(6); setSelected('search'); setSatellites(history.reduce((all, item) => ({ ...all, [item.target]: [...all[item.target], item] }), empty())); setPlaying(true); }, [mode]);
  useEffect(() => { if (!playing) return; const id = window.setInterval(() => setCursor((current) => { const next = current + 1; if (next >= currentSessionEvents.length) { setPlaying(false); return current; } queueMicrotask(() => run(next)); return next; }), 1200); return () => window.clearInterval(id); }, [playing, run]);
  const reset = () => { setPlaying(false); setCursor(-1); setBeam(null); setSatellites(empty()); };
  const inject = (name: string, kind: AgentEventKind, detail: string) => { const config = eventKinds[kind], next: AgentEvent = { id: `scene-${Date.now()}`, at: 0, kind, title: name, detail, target: config.zone }; setScene(name); setSelected(config.zone); setSatellites((old) => ({ ...old, [config.zone]: [...old[config.zone], next] })); const link = eventLinks[kind]; if (link) setBeam({ from: link[0], to: link[1], color: config.color, id: Date.now() }); };
  const metric = { context: `${(8.2 + Math.max(0, cursor + 1) * .31).toFixed(1)}k / 200k`, memory: cursor >= 14 ? '1 loaded' : '0 loaded', skills: cursor >= 2 ? '1 active' : '0 active', mcp: cursor >= 2 ? 'github · online' : 'offline' };
  return <><div className="star-field" /><header className="fixed inset-x-0 top-0 z-30 flex h-11 items-center justify-between border-b border-blue-200/10 bg-slate-950/75 px-[18px] backdrop-blur-md"><a href="/" className="text-[11px] tracking-[.16em] text-slate-100"><span className="text-blue-300">AGENT</span>VISUAL <span className="text-slate-500">/ {mode === 'material' ? 'material library' : 'session replay'}</span></a><nav className="flex gap-1"><Button variant="ghost" asChild><a href="/material"><Aperture size={13} />MATERIAL</a></Button><Button variant="ghost" onClick={() => setTilt((v) => !v)}><Telescope size={13} />FIELD TILT</Button><Button variant="ghost" onClick={reset}><RotateCcw size={13} />REPLAY</Button></nav></header>
  <aside className="fixed bottom-4 left-4 top-[60px] z-20 w-56 border border-blue-200/10 bg-slate-950/65 p-3.5 backdrop-blur-xl"><p className="mb-3 text-[9px] uppercase tracking-[.16em] text-blue-200/60">Live state</p>{[['Context', metric.context], ['Memory', metric.memory], ['Skills', metric.skills], ['MCP', metric.mcp]].map(([key, value]) => <div key={key} className="border-b border-blue-100/10 py-2.5 text-slate-400"><span>{key}</span><strong className="float-right font-medium text-blue-100">{value}</strong></div>)}<p className="mb-2 mt-5 text-[9px] uppercase tracking-[.16em] text-blue-200/60">Active tools</p>{['rg', 'read_file', 'apply_patch', 'github.search_code'].map((tool) => <span key={tool} className="mr-1 inline-block rounded-full border border-blue-200/15 px-1.5 py-0.5 text-[10px] text-slate-400">{tool}</span>)}</aside>
  <main className="execution-stage fixed bottom-[86px] left-64 right-[282px] top-11 z-10 overflow-hidden [perspective:950px]"><div className={`world ${tilt ? 'tilt' : ''}`}>{(Object.entries(zones) as [AgentZone, typeof zones[AgentZone]][]).map(([name, zone], index) => <div key={name} onClick={() => setSelected(name)} className={`zone ${selected === name ? 'selected' : ''} ${event?.target === name ? 'active' : ''} ${counts[name] ? 'populated' : ''}`} style={{ left: `${zone.x}%`, top: `${zone.y}%`, ['--rgb' as string]: zone.rgb, ['--speed' as string]: `${4 + index % 4}s`, ['--tilt' as string]: `${index * 23}deg`, scale: `${Math.min(1 + counts[name] * .04, 1.36)}` }}><i className="nebula-shell shell-a" /><i className="nebula-shell shell-b" /><i className="core" /><span className="zone-label">{name}</span>{particleMap[name].map((p) => <i className="field-particle" key={p.id} style={{ left: `${p.x}%`, top: `${p.y}%`, width: p.size, height: p.size, animationDelay: p.delay, animationDuration: p.duration }} />)}{satellites[name].map((item, n) => <i key={item.id} className="satellite" style={{ ['--duration' as string]: `${8 + n % 5 * 2}s`, ['--from' as string]: `${n * 53}deg`, ['--radius' as string]: `${36 + Math.min(n, 7) * 8}px` }}><small>{item.title === 'Read' || item.title === 'Patch' ? item.detail.split(' · ')[0] : item.title}</small>{n > 1 && <i className="satellite child" style={{ ['--duration' as string]: `${7 + n}s`, ['--from' as string]: `${n * 71}deg`, ['--radius' as string]: `${18 + n % 3 * 5}px` }} />}</i>)}</div>)}</div>{beam && <Beam beam={beam} />}</main>
  {mode === 'material' && <div className="material-deck fixed left-64 right-[282px] top-14 z-20"><span>SCENES</span>{scenes.map(([name, kind, detail]) => <Button key={kind} className={scene === name ? 'border-blue-200/70 bg-blue-950/80' : 'bg-slate-950/60'} onClick={() => inject(name, kind, detail)}>{name}</Button>)}</div>}
  <aside className="fixed bottom-4 right-4 top-[60px] z-20 w-[250px] border border-blue-200/10 bg-slate-950/65 p-3.5 backdrop-blur-xl"><p className="mb-3 text-[9px] uppercase tracking-[.16em] text-blue-200/60">{mode === 'material' ? 'Scene inspector' : 'Event inspector'}</p>{event ? <><Panel title={event.title} selected text={event.detail} /><Panel title={event.kind} text={`material: ${eventKinds[event.kind].effect}\ntarget: ${event.target}\nt + ${(event.at / 1000).toFixed(1)}s · ${cursor + 1}/${currentSessionEvents.length}`} /></> : <Panel title={scene ?? 'Replay ready'} text={scene ? 'Scene injected into the persistent field.' : 'The execution page starts with a populated field, then continues replaying.'} />}<p className="mb-2 mt-5 text-[9px] uppercase tracking-[.16em] text-blue-200/60">Visual semantics</p><Panel title="Mass" text="usage → radius, density, orbit complexity" /><Panel title="Beam" text="cross-system request / function call" /><Panel title="History" text="completed events stay as dim satellites" /></aside>
  <section className="fixed inset-x-0 bottom-0 z-30 grid h-[86px] grid-cols-[230px_1fr_245px] items-center gap-4 border-t border-blue-200/10 bg-slate-950/85 px-[18px] backdrop-blur-xl"><div className="flex gap-2"><Button onClick={() => { if (cursor >= currentSessionEvents.length - 1) reset(); setPlaying((v) => !v); }}>{playing ? <Pause size={13} /> : <Play size={13} />}{playing ? 'PAUSE' : 'PLAY'}</Button><Button onClick={() => run(cursor + 1)}>STEP</Button><Button onClick={reset}>RESET</Button></div><div className="flex h-10 items-center gap-[5px] overflow-hidden">{currentSessionEvents.map((item, index) => <button aria-label={item.detail} onClick={() => run(index)} key={item.id} className={`size-[7px] shrink-0 rounded-full transition-all ${index < cursor ? 'opacity-80' : index === cursor ? 'scale-[1.75] opacity-100' : 'opacity-30'}`} style={{ background: eventKinds[item.kind].color, boxShadow: `0 0 8px ${eventKinds[item.kind].color}` }} />)}</div><div className="overflow-hidden text-right text-[11px] text-slate-500"><b className="block font-medium text-blue-100">{event?.title ?? (mode === 'material' ? 'Material library' : 'Current project session')}</b>{event?.detail ?? (mode === 'material' ? 'Choose a scene to inject' : `${currentSessionEvents.length} sanitized events queued`)}</div></section></>;
}
function Panel({ title, text, selected = false }: { title: string; text: string; selected?: boolean }) { return <div className={`mb-3 border-l border-blue-200/30 bg-slate-900/35 p-2 text-[10px] ${selected ? 'outline outline-1 outline-offset-[5px] outline-blue-200/60' : ''}`}><b className="font-medium text-blue-100">{title}</b><p className="mb-0 mt-1 whitespace-pre-line text-slate-400">{text}</p></div>; }
function Beam({ beam }: { beam: Beam }) { const from = zones[beam.from], to = zones[beam.to], dx = to.x - from.x, dy = to.y - from.y; return <i key={beam.id} className="beam" style={{ left: `${from.x}%`, top: `${from.y}%`, width: `${Math.hypot(dx, dy)}%`, ['--beam' as string]: hex(beam.color), ['--angle' as string]: `${Math.atan2(dy, dx)}rad` }} />; }
function hex(value: string) { return `${parseInt(value.slice(1, 3), 16)},${parseInt(value.slice(3, 5), 16)},${parseInt(value.slice(5, 7), 16)}`; }
